### ISSUE TITLE
'PyInt_FromLong': identifier not found

### ISSUE THREAD

**Issue by rornor** [virtuald/python-tesseract-sip#4]
Hi, I'd like to build this module as it seems to work well with numpy/opencv source, but it's very hard to install. I run Windows 10 with 64 bit Python 3.6 and Visual Studio 2015.

First I pip installed sip, but it seems like this module expects sip.exe which is not installed through pip, so I needed to build sip from source. Ok, done.

Then I downloaded provided leptonica and tesseract dll files and made libs out of it, as explained in one of closed issues. After that I downloaded appropriate leptonica and tesseract sources to provide include files. And then I tried to build extension:

```
>python setup.py build_ext
running build_ext
building 'tesseract_sip' extension
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\tesseract_sip\python-tesseract-sip\src -IC:\tesseract_sip\python-tesseract-sip\sip -IC:\tesseract_sip\python-tesseract-sip\..\include -IC:\tesseract_sip\python-tesseract-sip\src\msvc -IC:\Python36\include -IC:\Python36\include -IC:\Python36\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\winrt" /EHsc /Tpbuild\temp.win-amd64-3.6\Release\siptesseract_sipcmodule.cpp /Fobuild\temp.win-amd64-3.6\Release\build\temp.win-amd64-3.6\Release\siptesseract_sipcmodule.obj /DWIN32 /EHsc
siptesseract_sipcmodule.cpp
c:\tesseract_sip\include\leptonica\environ.h(491): warning C4005: 'snprintf': macro redefinition
c:\python36\include\pyerrors.h(477): note: see previous definition of 'snprintf'
c:\tesseract_sip\include\leptonica\pix.h(210): warning C4305: 'initializing': truncation from 'double' to 'l_float32'
c:\tesseract_sip\include\leptonica\pix.h(212): warning C4305: 'initializing': truncation from 'double' to 'l_float32'
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\tesseract_sip\python-tesseract-sip\src -IC:\tesseract_sip\python-tesseract-sip\sip -IC:\tesseract_sip\python-tesseract-sip\..\include -IC:\tesseract_sip\python-tesseract-sip\src\msvc -IC:\Python36\include -IC:\Python36\include -IC:\Python36\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\winrt" /EHsc /Tpbuild\temp.win-amd64-3.6\Release\siptesseract_sipPix.cpp /Fobuild\temp.win-amd64-3.6\Release\build\temp.win-amd64-3.6\Release\siptesseract_sipPix.obj /DWIN32 /EHsc
siptesseract_sipPix.cpp
c:\tesseract_sip\include\leptonica\environ.h(491): warning C4005: 'snprintf': macro redefinition
c:\python36\include\pyerrors.h(477): note: see previous definition of 'snprintf'
c:\tesseract_sip\include\leptonica\pix.h(210): warning C4305: 'initializing': truncation from 'double' to 'l_float32'
c:\tesseract_sip\include\leptonica\pix.h(212): warning C4305: 'initializing': truncation from 'double' to 'l_float32'
sip/pix.sip(112): error C3861: 'PyInt_FromLong': identifier not found
sip/pix.sip(113): error C3861: 'PyInt_FromLong': identifier not found
sip/pix.sip(114): error C3861: 'PyInt_FromLong': identifier not found
sip/pix.sip(167): warning C4244: 'initializing': conversion from 'Py_ssize_t' to 'int', possible loss of data
sip/pix.sip(168): warning C4244: 'initializing': conversion from 'Py_ssize_t' to 'int', possible loss of data
sip/pix.sip(179): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
sip/pix.sip(239): warning C4018: '<': signed/unsigned mismatch
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
```

I'm not sure if it's not possible to build it with used versions or maybe I miss something else. Any ideas?

For reference this is my folder structure:

```
..
├───include
│   ├───leptonica
│   │       allheaders.h
│   │       alltypes.h
│   │       array.h
│   │       arrayaccess.h
│   │       bbuffer.h
│   │       bmf.h
│   │       ccbord.h
│   │       dewarp.h
│   │       environ.h
│   │       gplot.h
│   │       heap.h
│   │       imageio.h
│   │       jbclass.h
│   │       list.h
│   │       morph.h
│   │       pix.h
│   │       ptra.h
│   │       queue.h
│   │       recog.h
│   │       regutils.h
│   │       stack.h
│   │       stringcode.h
│   │       sudoku.h
│   │       watershed.h
│   │
│   └───tesseract
│           apitypes.h
│           baseapi.h
│           bits16.h
│           blamer.h
│           blckerr.h
│           boxword.h
│           clst.h
│           coutln.h
│           crakedge.h
│           elst.h
│           elst2.h
│           errcode.h
│           fontinfo.h
│           genericvector.h
│           helpers.h
│           host.h
│           ipoints.h
│           kdpair.h
│           lsterr.h
│           ltrresultiterator.h
│           matrix.h
│           memry.h
│           mod128.h
│           ndminx.h
│           ocrrow.h
│           pageiterator.h
│           params.h
│           params_training_featdef.h
│           platform.h
│           points.h
│           publictypes.h
│           quadratc.h
│           quspline.h
│           ratngs.h
│           rect.h
│           resultiterator.h
│           scrollview.h
│           serialis.h
│           stepblob.h
│           strngs.h
│           tesscallback.h
│           thresholder.h
│           tprintf.h
│           unichar.h
│           unicharset.h
│           werd.h
│
├───lib
│       liblept172.def
│       liblept172.dll
│       liblept172.exp
│       liblept172.lib
│       libtesseract304.def
│       libtesseract304.dll
│       libtesseract304.exp
│       libtesseract304.lib
│
└───python-tesseract-sip
```

Thanks

**Comment by virtuald** [comment]
I think PyInt_FromLong isn't defined in Python 3... I never tried this module with Python 3, so I suspect that's your issue. I don't use it anymore, so feel free to update it with #ifdefs and submit a PR. :)

**Comment by rornor** [comment]
Nice! That worked although not to the end. Now I get this error:

```
build\temp.win-amd64-3.6\Release\siptesseract_sipTessBaseAPI.cpp(1239): error C2664: 'bool tesseract::TessBaseAPI::ProcessPages(const char *,const char *,int,tesseract::TessResultRenderer *)': cannot convert argument 4 from 'STRING *' to 'tesseract::TessResultRenderer *'
build\temp.win-amd64-3.6\Release\siptesseract_sipTessBaseAPI.cpp(1239): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
```

Or here is full log:

```
>python setup.py build_ext
running build_ext
building 'tesseract_sip' extension
C:\Python36\sip.exe -g -e -I C:\tesseract_sip\python-tesseract-sip\sip -c build\temp.win-amd64-3.6\Release -b build\temp.win-amd64-3.6\Release\module.sbf -I C:\Python36\sip C:\tesseract_sip\python-tesseract-sip\sip\module.sip
creating build\temp.win-amd64-3.6\Release\build
creating build\temp.win-amd64-3.6\Release\build\temp.win-amd64-3.6
creating build\temp.win-amd64-3.6\Release\build\temp.win-amd64-3.6\Release
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\tesseract_sip\python-tesseract-sip\src -IC:\tesseract_sip\python-tesseract-sip\sip -IC:\tesseract_sip\python-tesseract-sip\..\include -IC:\tesseract_sip\python-tesseract-sip\src\msvc -IC:\Python36\include -IC:\Python36\include -IC:\Python36\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\winrt" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\winrt" /EHsc /Tpbuild\temp.win-amd64-3.6\Release\siptesseract_sipcmodule.cpp /Fobuild\temp.win-amd64-3.6\Release\build\temp.win-amd64-3.6\Release\siptesseract_sipcmodule.obj /DWIN32 /EHsc
siptesseract_sipcmodule.cpp
c:\projects\tesseract_sip\include\leptonica\environ.h(491): warning C4005: 'snprintf': macro redefinition
c:\python36\include\pyerrors.h(477): note: see previous definition of 'snprintf'
c:\projects\tesseract_sip\include\leptonica\pix.h(210): warning C4305: 'initializing': truncation from 'double' to 'l_float32'
c:\projects\tesseract_sip\include\leptonica\pix.h(212): warning C4305: 'initializing': truncation from 'double' to 'l_float32'
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\tesseract_sip\python-tesseract-sip\src -IC:\tesseract_sip\python-tesseract-sip\sip -IC:\tesseract_sip\python-tesseract-sip\..\include -IC:\tesseract_sip\python-tesseract-sip\src\msvc -IC:\Python36\include -IC:\Python36\include -IC:\Python36\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\winrt" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\winrt" /EHsc /Tpbuild\temp.win-amd64-3.6\Release\siptesseract_sipPix.cpp /Fobuild\temp.win-amd64-3.6\Release\build\temp.win-amd64-3.6\Release\siptesseract_sipPix.obj /DWIN32 /EHsc
siptesseract_sipPix.cpp
c:\projects\tesseract_sip\include\leptonica\environ.h(491): warning C4005: 'snprintf': macro redefinition
c:\python36\include\pyerrors.h(477): note: see previous definition of 'snprintf'
c:\projects\tesseract_sip\include\leptonica\pix.h(210): warning C4305: 'initializing': truncation from 'double' to 'l_float32'
c:\projects\tesseract_sip\include\leptonica\pix.h(212): warning C4305: 'initializing': truncation from 'double' to 'l_float32'
sip/pix.sip(167): warning C4244: 'initializing': conversion from 'Py_ssize_t' to 'int', possible loss of data
sip/pix.sip(168): warning C4244: 'initializing': conversion from 'Py_ssize_t' to 'int', possible loss of data
sip/pix.sip(179): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
sip/pix.sip(239): warning C4018: '<': signed/unsigned mismatch
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\tesseract_sip\python-tesseract-sip\src -IC:\tesseract_sip\python-tesseract-sip\sip -IC:\tesseract_sip\python-tesseract-sip\..\include -IC:\tesseract_sip\python-tesseract-sip\src\msvc -IC:\Python36\include -IC:\Python36\include -IC:\Python36\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\winrt" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\winrt" /EHsc /Tpbuild\temp.win-amd64-3.6\Release\siptesseract_sipPixBuffer.cpp /Fobuild\temp.win-amd64-3.6\Release\build\temp.win-amd64-3.6\Release\siptesseract_sipPixBuffer.obj /DWIN32 /EHsc
siptesseract_sipPixBuffer.cpp
c:\projects\tesseract_sip\include\leptonica\environ.h(491): warning C4005: 'snprintf': macro redefinition
c:\python36\include\pyerrors.h(477): note: see previous definition of 'snprintf'
c:\projects\tesseract_sip\include\leptonica\pix.h(210): warning C4305: 'initializing': truncation from 'double' to 'l_float32'
c:\projects\tesseract_sip\include\leptonica\pix.h(212): warning C4305: 'initializing': truncation from 'double' to 'l_float32'
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\x86_amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\tesseract_sip\python-tesseract-sip\src -IC:\tesseract_sip\python-tesseract-sip\sip -IC:\tesseract_sip\python-tesseract-sip\..\include -IC:\tesseract_sip\python-tesseract-sip\src\msvc -IC:\Python36\include -IC:\Python36\include -IC:\Python36\include "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\winrt" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\INCLUDE" "-IC:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\ATLMFC\INCLUDE" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.10240.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\\winrt" /EHsc /Tpbuild\temp.win-amd64-3.6\Release\siptesseract_sipTessBaseAPI.cpp /Fobuild\temp.win-amd64-3.6\Release\build\temp.win-amd64-3.6\Release\siptesseract_sipTessBaseAPI.obj /DWIN32 /EHsc
siptesseract_sipTessBaseAPI.cpp
c:\projects\tesseract_sip\include\leptonica\environ.h(491): warning C4005: 'snprintf': macro redefinition
c:\python36\include\pyerrors.h(477): note: see previous definition of 'snprintf'
c:\projects\tesseract_sip\include\leptonica\pix.h(210): warning C4305: 'initializing': truncation from 'double' to 'l_float32'
c:\projects\tesseract_sip\include\leptonica\pix.h(212): warning C4305: 'initializing': truncation from 'double' to 'l_float32'
build\temp.win-amd64-3.6\Release\siptesseract_sipTessBaseAPI.cpp(1239): error C2664: 'bool tesseract::TessBaseAPI::ProcessPages(const char *,const char *,int,tesseract::TessResultRenderer *)': cannot convert argument 4 from 'STRING *' to 'tesseract::TessResultRenderer *'
build\temp.win-amd64-3.6\Release\siptesseract_sipTessBaseAPI.cpp(1239): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
sip/baseapi.sip(631): warning C4244: '=': conversion from '__int64' to 'int', possible loss of data
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\cl.exe' failed with exit status 2
```

**Comment by rornor** [comment]
It builds fine with older versions: leptonica 1.68 and tesseract 3.02
