### ISSUE TITLE
Compatibility with newer tesseract versions

### ISSUE THREAD

**Issue by rornor** [virtuald/python-tesseract-sip#6]
It seems this module works with hardcoded tesseract 3.02, but does not build with newer versions, probably because of changes in some methods, i.e.:

```
build\temp.win-amd64-3.6\Release\siptesseract_sipTessBaseAPI.cpp(1239): error C2664: 'bool tesseract::TessBaseAPI::ProcessPages(const char *,const char *,int,tesseract::TessResultRenderer *)': cannot convert argument 4 from 'STRING *' to 'tesseract::TessResultRenderer *'
build\temp.win-amd64-3.6\Release\siptesseract_sipTessBaseAPI.cpp(1239): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
```

Currently, tessdata files are available starting from tesseract 3.04, but focused on tesseract 4.0 (https://github.com/tesseract-ocr/tessdata)

tessdata files for 3.02 can be found archived on Internet: https://sourceforge.net/projects/tesseract-ocr-alt/

It would be great if someone can glue new tesseract version with sip, as IMHO this is the best Python interface to tesseract available, yet no so popular for some reason.
